# Generated by Django 3.0.8 on 2021-05-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
